Air fryer
tuya/tuya-home-assistant pull request #156
Opened 2021-07-16 16:39 UTC by Sthopeless

Adding support for Air Fryer (kqzg) Switches (Turn On/Off and Start/Pause)

2021-07-16 17:37 UTC, Sthopeless commented
Zigbee Doorlock (ms) Doorbell Volume 

![Screenshot (128)](https://user-images.githubusercontent.com/6695214/125987279-e8e0da9a-c2b2-46a4-9e99-4a61f651f195.png)

2021-07-18 21:15 UTC, Jhonattan-Souza requested changes

2021-07-18 21:15 UTC, Jhonattan-Souza commented on custom_components/tuya_v2/select.py
>  #!/usr/bin/env python3
I think you've made a mistake here, this is not the number entity file, is the SelectEntity file, you're removing functionalities from the library

2021-07-18 21:36 UTC, Sthopeless commented on custom_components/tuya_v2/select.py
>  #!/usr/bin/env python3
sorry somehow confused one file with the other.. fixed below

2021-07-23 02:13 UTC, tsutsuku commented on custom_components/tuya_v2/switch.py
> +DPCODE_AIRFRYER_SPIN = "spin_switch"
According to doc spin_switch data type is Integer, why put it in the switch.py?

2021-07-23 05:27 UTC, Sthopeless commented on custom_components/tuya_v2/switch.py
> +DPCODE_AIRFRYER_SPIN = "spin_switch"
@tsutsuku I noticed documentation said integer but at least on mine testing Air Fryer is shows as a boolean, check last option:
![Screenshot_2021-07-23-07-24-09-009_com tuya smartlife](https://user-images.githubusercontent.com/6695214/126740689-72e54202-cc82-444d-9450-33af7334c89c.jpg)

2021-07-23 06:17 UTC, Sthopeless commented
this is enabled no other option/configuration available for me
![Screenshot_2021-07-23-08-16-15-976_com tuya smartlife](https://user-images.githubusercontent.com/6695214/126744039-d9ab3b12-7905-44c7-bb9f-8353b5994774.jpg)

2021-07-26 09:11 UTC, Sthopeless commented
@tsutsuku is the `spin_switch` being checked?  
In Home Assistant if I set it to integer nothing happens it only works as a boolean switch.

Smartlife only has On/Off option.

On [cloud explorer](https://iot.tuya.com/cloud/explorer) I see it as a integer 
but I try to change the value I get a error saying `type is incorrect` also nothing happens in Smartlife app or Home Assistant logs

<img src="https://user-images.githubusercontent.com/6695214/126964130-c3888cc2-14fb-4616-8aba-e6ce09470fb7.png" width="100%" height="100%">

2021-07-31 18:55 UTC, closed without merging